import type { Route } from '../../types/travel'

export const initialRoutes: Route[] = [
  {
    id: 1,
    title: 'Альпийская панорама',
    cover: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=80',
    cities: ['Инсбрук', 'Больцано', 'Церматт'],
    durationDays: 8,
    transport: 'Поезд',
    saves: 421,
    author: 'Елена Маркова',
    country: 'Австрия, Италия, Швейцария',
    isNew: false,
  },
  {
    id: 2,
    title: 'Средиземноморский уикенд',
    cover: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    cities: ['Барселона', 'Валенсия', 'Пальма'],
    durationDays: 5,
    transport: 'Самолёт',
    saves: 387,
    author: 'Артём Данилов',
    country: 'Испания',
    isNew: true,
  },
  {
    id: 3,
    title: 'Норвежские фьорды',
    cover: 'https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=1400&q=80',
    cities: ['Берген', 'Флом', 'Осло'],
    durationDays: 7,
    transport: 'Автомобиль',
    saves: 512,
    author: 'Мария Тихонова',
    country: 'Норвегия',
    isSaved: true,
  },
  {
    id: 4,
    title: 'Пешком по Стамбулу',
    cover: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1400&q=80',
    cities: ['Кадыкёй', 'Султанахмет', 'Галата'],
    durationDays: 3,
    transport: 'Пешком',
    saves: 204,
    author: 'Илья Шестаков',
    country: 'Турция',
    isNew: true,
  },
]
